right_format = """$sudo$time"""

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'
vicmd_symbol = "[V](bold green) "

[username]
style_user = "bold purple"
style_root = "bold red"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "(bold)[@](bold)[$hostname](bold yellow) "
disabled = false

[cmd_duration]
disabled = true

[directory]
truncate_to_repo = false

[sudo]
format = '[$symbol]($style)'
symbol = "üêß "
disabled = false

[time]
disabled = false
use_12hr = false
format = '[$time]($style)'
time_format = "%T"
utc_time_offset = "local"

[[battery.display]]
threshold = 15
style = "bold red"

[memory_usage]
disabled = false
format = '[$ram]($style) '
threshold = 75
symbol = " "
style = "bold white"

